# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 12 May 2011 19:16:09 -0400
*               @ALL          0
*               @user         8
